hyperoslo/Sugar

Source/Functions.swift
This PR adds some functionality to `dispatch`.
Now you can select between all global queues by just passing an enum value;
It still defaults to `.Main` so the public API does not change.
```swift
dispatch {}
dispatch(queue: .Interactive) {}
dispatch(queue: .Initiated) {}
dispatch(queue: .Utility) {}
dispatch(queue: .Background) {}
```
As an added bonus, if you need your own custom queue you can just do the following;
```swift
dispatch(queue: .Custom(myQueue)) {}
```
=> Add support for all global queues

Source/iOS/Extensions/UICollectionView+Indexes.swift, Source/iOS/Extensions/UITableView+Indexes.swift, Sugar.xcodeproj/project.pbxproj
This PR adds some sugars for inserting, updating and deleting indexes on a `UITableView` or `UICollectionView`.
```swift
public extension UICollectionView {
func insert(indexes: [Int], section: Int = 0, completion: (() -> Void)? = nil) {}
func reload(indexes: [Int], section: Int = 0, completion: (() -> Void)? = nil) {}
func remove(indexes: [Int], section: Int = 0, completion: (() -> Void)? = nil) {}
func reloadSection(index: Int = 0, completion: (() -> Void)? = nil) {}
}
public extension UITableView {
func insert(indexes: [Int], section: Int = 0, animation: UITableViewRowAnimation = .None) {}
func reload(indexes: [Int], section: Int = 0, animation: UITableViewRowAnimation = .None) {}
func remove(indexes: [Int], section: Int = 0, animation: UITableViewRowAnimation = .None) {}
func …
```
=> Add collection and table view sugars

Source/Shared/Extensions/String+CoreFoundation.swift
This PR refactors `.split` on `String`.
If `componentsSeparatedByString` in unable to split the current target into components it
will return `[]` instead of `[""]`.
=> Refactor split method on String

Source/Shared/Extensions/String+CoreFoundation.swift
It felt a bit overkill to have an early return in such a small method.
Now the statement is a part of the `return` which renders it equally clear.
```swift
func truncate(length: Int, suffix: String = "...") -> String {
return self.characters.count > length
? self.substringToIndex(self.startIndex.advancedBy(length)) + suffix
: self
}
```
https://github.com/hyperoslo/Sugar/pull/29 should be merged before this PR.
=> Refactor String.truncate

Source/iOS/Extensions/UITableView+Indexes.swift
This PR fixes the use of animation when making updates on a `UITableView`.
There is also a new default for calling the functions, instead of using `.None`, it defaults to `.Automatic`.
=> Improve UITableView+Indexes extension

Source/Shared/Localization.swift
This PR refactors the `localizedString` method so that you can specify which bundle you would like to open the string from.
You do this by sending in the class of the current UI component using the string.
```swift
UILabel.text = localizedString("Contact.Email", self.classForCoder)
```
=> Improve localizedString method

Source/iOS/Extensions/UITableView+Indexes.swift
This PR removes the animation when updating a table view if `animation` is set to `.None`.
=> Remove animations if animations is .None

Source/Shared/Result.swift, Sugar.xcodeproj/project.pbxproj
This PR adds a generic result type that is nifty to use when building functions that `throw`
=> Add result enum

Source/iOS/Extensions/UIDevice.swift, Sugar.xcodeproj/project.pbxproj
Adding iPhone only, because don't really need iPad at the moment.
=> UIDevice extension to return device model

Source/Shared/Extensions/String+CoreFoundation.swift
This is the reverse of `isEmpty` but it will help improve the
implementation in your application.
So instead of:
```swift
if !value.isEmpty {}
```
You could do:
```swift
if value.isPresent {}
```
=> Add/isPresent on String

Source/iOS/Extensions/UIDevice+Model.swift
1. Added function `isIPhone` and `isIPad`.
When working on Universal application these are very useful.
2. Added function `isSimulator`
This was already present in `Sugar` via `Simulator`. Just added convenient method here.
=> Added isIPhone, isIPad, isSimulator methods to UIDevice+Model

README.md, Source/Shared/Localization.swift
Now you can localize formatted string with arguments:
`localizedString(key: "%d numbers", arguments: 10)`
=> Implement localized string with arguments

README.md, Source/Shared/Extensions/Range+Contains.swift, Source/iOS/Extensions/Range+Contains.swift
I was doing some Networking and wanted to check if the status code was in a range, did this tiny thing. You call it like this:
```swift
let OK = 200..<300
OK.contains(response.statusCode)
```
@hyperoslo/malibu
=> Contains method in Range

Source/Shared/Localization.swift
This PR fixes a compiler error that is introduced with Swift 3.0.1.
=> Rename method to fix compiler error with Swift 3.0.1

Source/Shared/Localization.swift
As of https://github.com/hyperoslo/Sugar/pull/90
I see that these 2 methods could cause confusion, and we can get infinite recursive calls within `localizeString`, so it's best to remove this.
Users can use the built in Swift function to create string`String(format: localizedString("some_key", arg[0], arg[1])`, it handles number of arguments for us
=> Remove localizeString function

Source/iOS/Constraint.swift, Sugar.xcodeproj/project.pbxproj
As iOS 9 is coming to as the default minimum deployment target, we're starting to use `NSLayoutAnchor` and stop dropping other Auto Layout helper libraries. However, we will do 2 repetitive steps as we're using `NSLayoutAnchor`
- Activate the constraints
- Set `translatesAutoresizingMaskIntoConstraints` to false
which is very easy to forget and boilerplate. This makes it into Sugar.
Also, it also opens up discussions as what we will improve Sugar as of Swift 3 😎
=> Add Constraint to handle constraint anchors

Source/iOS/Constraint.swift
Ok, the last time I hope 😄 
1) Xcode wasn't happy with variadic vars when it comes to indentation, I think this should work:
```swift
Constraint.on(
imageView.topAnchor.constraint(equalTo: view.topAnchor),
)
```
2) Add optional insets when you want to pin edges.
=> Improve constrant methods

Source/Shared/Application.swift
Fallback to `CFBundleName` in case `CFBundleDisplayName` is not specified in `Info.plist`
=> Fix bundle name

Source/iOS/Utilities.swift, Sugar.xcodeproj/project.pbxproj
This method can come in handy when we need to check if push notification can really be delivered to the app
=> Add isPushNotificationEnabled

Source/Shared/Extensions/NSDate+Extensions.swift
If you use current Sugar with Swift 3 environment and use `>`, `<`, `>=`, `<=` operators, it will lead to compile error like follows. 
```
Ambiguous use of operator '<'
```
We shouldn't have these operators in Sugar anymore.
=> Swift 3 Date is comparable. These operators will conflict with Swift 3 operators.

Source/iOS/Extensions/UIImage+RenderingMode.swift, Tests/iOS/TestUIImage.swift
It can crashes if the image is not really an image
=> Check for content before apply templating

Source/iOS/Extensions/UIDevice+Model.swift
- As of https://github.com/onmyway133/blog/issues/59, we shouldn't use `nativeBounds`, as it is physical sizes, and devices also have `display mode`
- Also, this advocates users to depend on specific devices to layout, which is not good practice 🙄 
- Remove it 😄
=> Remove sizes

Source/Shared/Extensions/String+Regex.swift
The former regex would match `foo@foo.com.` too.
=> Fix email validation

README.md
I found this nice library and at first I saw that it's for Swift 3 (icon) but in the end it's for Swift 4.0.
=> Swift 4 for img shield icon
